$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: solar-deployment
endpoint_name: solar-endpoint
model: azureml:solar-generation-model:1
environment: acr://energydashacr.azurecr.io/energy-dashboard:py3.11
code_configuration:
  code: src
  scoring_script: score.py
instance_type: Standard_DS3_v2
scale_settings:
  type: target_utilization
  min_replicas: 1
  max_replicas: 3
  target_utilization: 70
