# .github/deployments/deploy.yml
$schema: https://azuremlschemas.azureedge.net/latest/onlineDeployment.schema.json
name: solar-generation-deployment-v1
endpoint_name: solar-endpoint
model: azureml:solar-generation-model:1
environment: azureml:solar-generation-env:11
code_configuration:
  code: ../../.github/environments/src
  scoring_script: score.py
instance_type: Standard_F2s_v2  # <---Normaly use Standard_DS1_v2
instance_count: 1
